@startuml
abstract class Beverage {
    description
    getDescription()
    cost()
}
package MainDrink <<Rectangle>> {
    class HouseBlend extends Beverage {
        cost()
    }
    class DarkRoast extends Beverage {
        cost()
    }
    class Espresso extends Beverage {
        cost()
    }
    class Decaf extends Beverage {
        cost()
    }
}

package Condiment <<Rectangle>> {
    abstract CondimentDecorator extends Beverage {
    getDescription()
    }

    class Milk extends CondimentDecorator {
        Beverage beverage 
        cost()
        getDescription()
    }

    class Mocha extends CondimentDecorator {
        Beverage beverage 
        cost()
        getDescription()
    }

    class Soy extends CondimentDecorator {
        Beverage beverage 
        cost()
        getDescription()
    }

    class Whip extends CondimentDecorator {
        Beverage beverage 
        cost()
        getDescription()
    }
}
CondimentDecorator --> Beverage : component

@enduml